export type AssetCategory = "crypto" | "stocks" | "commodities" | "forex";

export interface MarketInfo {
  marketId: number;
  symbol: string;
  label: string;
  dex: string;
  category: AssetCategory;
  name: string;
}

export const MARKETS: MarketInfo[] = [
  { marketId: 1, symbol: "BTC", label: "BTC / USD", dex: "", category: "crypto", name: "Bitcoin" },
  { marketId: 2, symbol: "ETH", label: "ETH / USD", dex: "", category: "crypto", name: "Ethereum" },
  { marketId: 3, symbol: "SOL", label: "SOL / USD", dex: "", category: "crypto", name: "Solana" },
  { marketId: 4, symbol: "HYPE", label: "HYPE / USD", dex: "", category: "crypto", name: "Hyperliquid" },
  { marketId: 14, symbol: "DOGE", label: "DOGE / USD", dex: "", category: "crypto", name: "Dogecoin" },
  { marketId: 15, symbol: "AVAX", label: "AVAX / USD", dex: "", category: "crypto", name: "Avalanche" },
  { marketId: 16, symbol: "ARB", label: "ARB / USD", dex: "", category: "crypto", name: "Arbitrum" },
  { marketId: 17, symbol: "AAVE", label: "AAVE / USD", dex: "", category: "crypto", name: "Aave" },
  { marketId: 5, symbol: "AAPL", label: "AAPL / USD", dex: "xyz", category: "stocks", name: "Apple Inc." },
  { marketId: 6, symbol: "NVDA", label: "NVDA / USD", dex: "xyz", category: "stocks", name: "NVIDIA Corp." },
  { marketId: 7, symbol: "TSLA", label: "TSLA / USD", dex: "xyz", category: "stocks", name: "Tesla Inc." },
  { marketId: 8, symbol: "COIN", label: "COIN / USD", dex: "xyz", category: "stocks", name: "Coinbase Global" },
  { marketId: 18, symbol: "MSFT", label: "MSFT / USD", dex: "xyz", category: "stocks", name: "Microsoft" },
  { marketId: 19, symbol: "GOOGL", label: "GOOGL / USD", dex: "xyz", category: "stocks", name: "Alphabet" },
  { marketId: 20, symbol: "AMZN", label: "AMZN / USD", dex: "xyz", category: "stocks", name: "Amazon" },
  { marketId: 21, symbol: "META", label: "META / USD", dex: "xyz", category: "stocks", name: "Meta Platforms" },
  { marketId: 9, symbol: "GOLD", label: "Gold (XAU)", dex: "xyz", category: "commodities", name: "Gold" },
  { marketId: 10, symbol: "SILVER", label: "Silver (XAG)", dex: "xyz", category: "commodities", name: "Silver" },
  { marketId: 11, symbol: "BRENTOIL", label: "Brent Oil", dex: "xyz", category: "commodities", name: "Brent Crude Oil" },
  { marketId: 22, symbol: "COPPER", label: "Copper / USD", dex: "xyz", category: "commodities", name: "Copper" },
  { marketId: 23, symbol: "PLATINUM", label: "Platinum", dex: "xyz", category: "commodities", name: "Platinum" },
  { marketId: 24, symbol: "PALLADIUM", label: "Palladium", dex: "xyz", category: "commodities", name: "Palladium" },
  { marketId: 12, symbol: "EUR", label: "EUR / USD", dex: "xyz", category: "forex", name: "Euro" },
  { marketId: 13, symbol: "JPY", label: "JPY / USD", dex: "xyz", category: "forex", name: "Japanese Yen" },
  { marketId: 25, symbol: "SP500", label: "S&P 500", dex: "xyz", category: "stocks", name: "S&P 500 Index" },
  { marketId: 26, symbol: "DXY", label: "DXY / USD", dex: "xyz", category: "forex", name: "US Dollar Index" },
  { marketId: 27, symbol: "AAOI", label: "AAOI / USD", dex: "xyz", category: "stocks", name: "AAOI" },
  { marketId: 28, symbol: "ALUMINIUM", label: "ALUMINIUM / USD", dex: "xyz", category: "commodities", name: "ALUMINIUM" },
  { marketId: 29, symbol: "AMAT", label: "AMAT / USD", dex: "xyz", category: "stocks", name: "AMAT" },
  { marketId: 30, symbol: "AMD", label: "AMD / USD", dex: "xyz", category: "stocks", name: "AMD" },
  { marketId: 31, symbol: "ARM", label: "ARM / USD", dex: "xyz", category: "stocks", name: "ARM" },
  { marketId: 32, symbol: "ASML", label: "ASML / USD", dex: "xyz", category: "stocks", name: "ASML" },
  { marketId: 33, symbol: "AVGO", label: "AVGO / USD", dex: "xyz", category: "stocks", name: "AVGO" },
  { marketId: 34, symbol: "BABA", label: "BABA / USD", dex: "xyz", category: "stocks", name: "BABA" },
  { marketId: 35, symbol: "BB", label: "BB / USD", dex: "xyz", category: "stocks", name: "BB" },
  { marketId: 36, symbol: "BE", label: "BE / USD", dex: "xyz", category: "stocks", name: "BE" },
  { marketId: 37, symbol: "BIRD", label: "BIRD / USD", dex: "xyz", category: "stocks", name: "BIRD" },
  { marketId: 38, symbol: "BOT", label: "BOT / USD", dex: "xyz", category: "stocks", name: "BOT" },
  { marketId: 39, symbol: "BX", label: "BX / USD", dex: "xyz", category: "stocks", name: "BX" },
  { marketId: 40, symbol: "CBRS", label: "CBRS / USD", dex: "xyz", category: "stocks", name: "CBRS" },
  { marketId: 41, symbol: "CL", label: "CL / USD", dex: "xyz", category: "commodities", name: "CL" },
  { marketId: 42, symbol: "CORN", label: "CORN / USD", dex: "xyz", category: "commodities", name: "CORN" },
  { marketId: 43, symbol: "COST", label: "COST / USD", dex: "xyz", category: "stocks", name: "COST" },
  { marketId: 44, symbol: "CRCL", label: "CRCL / USD", dex: "xyz", category: "stocks", name: "CRCL" },
  { marketId: 45, symbol: "CRWD", label: "CRWD / USD", dex: "xyz", category: "stocks", name: "CRWD" },
  { marketId: 46, symbol: "CRWV", label: "CRWV / USD", dex: "xyz", category: "stocks", name: "CRWV" },
  { marketId: 47, symbol: "CXMT", label: "CXMT / USD", dex: "xyz", category: "stocks", name: "CXMT" },
  { marketId: 48, symbol: "DELL", label: "DELL / USD", dex: "xyz", category: "stocks", name: "DELL" },
  { marketId: 49, symbol: "DKNG", label: "DKNG / USD", dex: "xyz", category: "stocks", name: "DKNG" },
  { marketId: 50, symbol: "DRAM", label: "DRAM / USD", dex: "xyz", category: "commodities", name: "DRAM" },
  { marketId: 51, symbol: "EBAY", label: "EBAY / USD", dex: "xyz", category: "stocks", name: "EBAY" },
  { marketId: 52, symbol: "EWJ", label: "EWJ / USD", dex: "xyz", category: "stocks", name: "EWJ" },
  { marketId: 53, symbol: "EWT", label: "EWT / USD", dex: "xyz", category: "stocks", name: "EWT" },
  { marketId: 54, symbol: "EWY", label: "EWY / USD", dex: "xyz", category: "stocks", name: "EWY" },
  { marketId: 55, symbol: "EWZ", label: "EWZ / USD", dex: "xyz", category: "stocks", name: "EWZ" },
  { marketId: 56, symbol: "GBP", label: "GBP / USD", dex: "xyz", category: "forex", name: "GBP" },
  { marketId: 57, symbol: "GEV", label: "GEV / USD", dex: "xyz", category: "stocks", name: "GEV" },
  { marketId: 58, symbol: "GIGADEV", label: "GIGADEV / USD", dex: "xyz", category: "stocks", name: "GIGADEV" },
  { marketId: 59, symbol: "GME", label: "GME / USD", dex: "xyz", category: "stocks", name: "GME" },
  { marketId: 60, symbol: "H100", label: "H100 / USD", dex: "xyz", category: "stocks", name: "H100" },
  { marketId: 61, symbol: "HIMS", label: "HIMS / USD", dex: "xyz", category: "stocks", name: "HIMS" },
  { marketId: 62, symbol: "HOOD", label: "HOOD / USD", dex: "xyz", category: "stocks", name: "HOOD" },
  { marketId: 63, symbol: "HYUNDAI", label: "HYUNDAI / USD", dex: "xyz", category: "stocks", name: "HYUNDAI" },
  { marketId: 64, symbol: "IBIDEN", label: "IBIDEN / USD", dex: "xyz", category: "stocks", name: "IBIDEN" },
  { marketId: 65, symbol: "IBM", label: "IBM / USD", dex: "xyz", category: "stocks", name: "IBM" },
  { marketId: 66, symbol: "IBOV", label: "IBOV / USD", dex: "xyz", category: "stocks", name: "IBOV" },
  { marketId: 67, symbol: "INTC", label: "INTC / USD", dex: "xyz", category: "stocks", name: "INTC" },
  { marketId: 68, symbol: "IREN", label: "IREN / USD", dex: "xyz", category: "stocks", name: "IREN" },
  { marketId: 69, symbol: "JP225", label: "JP225 / USD", dex: "xyz", category: "stocks", name: "JP225" },
  { marketId: 70, symbol: "KIOXIA", label: "KIOXIA / USD", dex: "xyz", category: "stocks", name: "KIOXIA" },
  { marketId: 71, symbol: "KORU", label: "KORU / USD", dex: "xyz", category: "stocks", name: "KORU" },
  { marketId: 72, symbol: "KR200", label: "KR200 / USD", dex: "xyz", category: "stocks", name: "KR200" },
  { marketId: 73, symbol: "KRW", label: "KRW / USD", dex: "xyz", category: "forex", name: "KRW" },
  { marketId: 74, symbol: "KSTR", label: "KSTR / USD", dex: "xyz", category: "stocks", name: "KSTR" },
  { marketId: 75, symbol: "LITE", label: "LITE / USD", dex: "xyz", category: "stocks", name: "LITE" },
  { marketId: 76, symbol: "LLY", label: "LLY / USD", dex: "xyz", category: "stocks", name: "LLY" },
  { marketId: 77, symbol: "LYTE", label: "LYTE / USD", dex: "xyz", category: "stocks", name: "LYTE" },
  { marketId: 78, symbol: "MAGS", label: "MAGS / USD", dex: "xyz", category: "stocks", name: "MAGS" },
  { marketId: 79, symbol: "MINIMAX", label: "MINIMAX / USD", dex: "xyz", category: "stocks", name: "MINIMAX" },
  { marketId: 80, symbol: "MRNA", label: "MRNA / USD", dex: "xyz", category: "stocks", name: "MRNA" },
  { marketId: 81, symbol: "MRVL", label: "MRVL / USD", dex: "xyz", category: "stocks", name: "MRVL" },
  { marketId: 82, symbol: "MSTR", label: "MSTR / USD", dex: "xyz", category: "stocks", name: "MSTR" },
  { marketId: 83, symbol: "MU", label: "MU / USD", dex: "xyz", category: "stocks", name: "MU" },
  { marketId: 84, symbol: "NATGAS", label: "NATGAS / USD", dex: "xyz", category: "commodities", name: "NATGAS" },
  { marketId: 85, symbol: "NBIS", label: "NBIS / USD", dex: "xyz", category: "stocks", name: "NBIS" },
  { marketId: 86, symbol: "NCLD", label: "NCLD / USD", dex: "xyz", category: "stocks", name: "NCLD" },
  { marketId: 87, symbol: "NET", label: "NET / USD", dex: "xyz", category: "stocks", name: "NET" },
  { marketId: 88, symbol: "NFLX", label: "NFLX / USD", dex: "xyz", category: "stocks", name: "NFLX" },
  { marketId: 89, symbol: "NIFTY", label: "NIFTY / USD", dex: "xyz", category: "stocks", name: "NIFTY" },
  { marketId: 90, symbol: "NOK", label: "NOK / USD", dex: "xyz", category: "stocks", name: "NOK" },
  { marketId: 91, symbol: "NOW", label: "NOW / USD", dex: "xyz", category: "stocks", name: "NOW" },
  { marketId: 92, symbol: "ORCL", label: "ORCL / USD", dex: "xyz", category: "stocks", name: "ORCL" },
  { marketId: 93, symbol: "PLTR", label: "PLTR / USD", dex: "xyz", category: "stocks", name: "PLTR" },
  { marketId: 94, symbol: "PURRDAT", label: "PURRDAT / USD", dex: "xyz", category: "stocks", name: "PURRDAT" },
  { marketId: 95, symbol: "QCOM", label: "QCOM / USD", dex: "xyz", category: "stocks", name: "QCOM" },
  { marketId: 96, symbol: "QNT", label: "QNT / USD", dex: "xyz", category: "stocks", name: "QNT" },
  { marketId: 97, symbol: "RDDT", label: "RDDT / USD", dex: "xyz", category: "stocks", name: "RDDT" },
  { marketId: 98, symbol: "RIVN", label: "RIVN / USD", dex: "xyz", category: "stocks", name: "RIVN" },
  { marketId: 99, symbol: "RKLB", label: "RKLB / USD", dex: "xyz", category: "stocks", name: "RKLB" },
  { marketId: 100, symbol: "SHAZ", label: "SHAZ / USD", dex: "xyz", category: "stocks", name: "SHAZ" },
  { marketId: 101, symbol: "SHEIN", label: "SHEIN / USD", dex: "xyz", category: "stocks", name: "SHEIN" },
  { marketId: 102, symbol: "SKHX", label: "SKHX / USD", dex: "xyz", category: "stocks", name: "SKHX" },
  { marketId: 103, symbol: "SKHY", label: "SKHY / USD", dex: "xyz", category: "stocks", name: "SKHY" },
  { marketId: 104, symbol: "SMH", label: "SMH / USD", dex: "xyz", category: "stocks", name: "SMH" },
  { marketId: 105, symbol: "SMSN", label: "SMSN / USD", dex: "xyz", category: "stocks", name: "SMSN" },
  { marketId: 106, symbol: "SNDK", label: "SNDK / USD", dex: "xyz", category: "stocks", name: "SNDK" },
  { marketId: 107, symbol: "SOFTBANK", label: "SOFTBANK / USD", dex: "xyz", category: "stocks", name: "SOFTBANK" },
  { marketId: 108, symbol: "SOXL", label: "SOXL / USD", dex: "xyz", category: "stocks", name: "SOXL" },
  { marketId: 109, symbol: "SPCX", label: "SPCX / USD", dex: "xyz", category: "stocks", name: "SPCX" },
  { marketId: 110, symbol: "STRC", label: "STRC / USD", dex: "xyz", category: "stocks", name: "STRC" },
  { marketId: 111, symbol: "TSM", label: "TSM / USD", dex: "xyz", category: "stocks", name: "TSM" },
  { marketId: 112, symbol: "TTF", label: "TTF / USD", dex: "xyz", category: "commodities", name: "TTF" },
  { marketId: 113, symbol: "UNITREE", label: "UNITREE / USD", dex: "xyz", category: "stocks", name: "UNITREE" },
  { marketId: 114, symbol: "URANIUM", label: "URANIUM / USD", dex: "xyz", category: "commodities", name: "URANIUM" },
  { marketId: 115, symbol: "URNM", label: "URNM / USD", dex: "xyz", category: "stocks", name: "URNM" },
  { marketId: 116, symbol: "USAR", label: "USAR / USD", dex: "xyz", category: "stocks", name: "USAR" },
  { marketId: 117, symbol: "VIX", label: "VIX / USD", dex: "xyz", category: "stocks", name: "VIX" },
  { marketId: 118, symbol: "VOL", label: "VOL / USD", dex: "xyz", category: "stocks", name: "VOL" },
  { marketId: 119, symbol: "WDC", label: "WDC / USD", dex: "xyz", category: "stocks", name: "WDC" },
  { marketId: 120, symbol: "WHEAT", label: "WHEAT / USD", dex: "xyz", category: "commodities", name: "WHEAT" },
  { marketId: 121, symbol: "XBI", label: "XBI / USD", dex: "xyz", category: "stocks", name: "XBI" },
  { marketId: 122, symbol: "XLE", label: "XLE / USD", dex: "xyz", category: "stocks", name: "XLE" },
  { marketId: 123, symbol: "XYZ100", label: "XYZ100 / USD", dex: "xyz", category: "stocks", name: "XYZ100" },
  { marketId: 124, symbol: "ZHIPU", label: "ZHIPU / USD", dex: "xyz", category: "stocks", name: "ZHIPU" },
  { marketId: 125, symbol: "ZM", label: "ZM / USD", dex: "xyz", category: "stocks", name: "ZM" },
];

export const MARKET_BY_ID = new Map(MARKETS.map((m) => [m.marketId, m]));
export const MARKET_BY_SYMBOL = new Map(MARKETS.map((m) => [m.symbol, m]));

export function getMarket(marketId: number): MarketInfo | undefined {
  return MARKET_BY_ID.get(marketId);
}
export function getMarketBySymbol(symbol: string): MarketInfo | undefined {
  return MARKET_BY_SYMBOL.get(symbol);
}
export const SUPPORTED_ASSET_IDS = MARKETS.map((m) => m.marketId);
export const SUPPORTED_SYMBOLS = MARKETS.map((m) => m.symbol);

export const BASE_PRICES: Record<string, number> = {
  BTC: 87450.00,
  ETH: 2480.00,
  SOL: 185.50,
  HYPE: 52.40,
  DOGE: 0.165,
  AVAX: 28.50,
  ARB: 0.58,
  AAVE: 165.00,
  AAPL: 232.00,
  NVDA: 138.50,
  TSLA: 245.00,
  COIN: 215.00,
  MSFT: 425.00,
  GOOGL: 178.00,
  AMZN: 195.00,
  META: 580.00,
  GOLD: 2742.50,
  SILVER: 31.80,
  BRENTOIL: 74.20,
  COPPER: 4.35,
  PLATINUM: 980.00,
  PALLADIUM: 1040.00,
  EUR: 1.085,
  JPY: 152.40,
  SP500: 5850.00,
  DXY: 104.20,
};

export function getMarketBasePrice(symbol: string): number {
  return BASE_PRICES[symbol.toUpperCase()] ?? 100.00;
}
