//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
pub struct LeveragedPredictionDecoder;
pub const PROGRAM_ID: Pubkey =
    solana_pubkey::Pubkey::from_str_const("CPUwSRL2h3mh27GutZ3k6hcHt4swrV1NcQAUuLQUbQYX");

pub mod accounts;
pub mod events;
pub mod instructions;
pub mod types;
